networks:
  bugnet:
    driver: bridge

services:
  db:
    image: mysql:9.3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bugtracker
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bugnet
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: "db:3306"
      DB_USER: bugger
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: bugtracker
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-15}
      REFRESH_TOKEN_EXPIRE_MINUTES: ${REFRESH_TOKEN_EXPIRE_MINUTES:-1440}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - bugnet
    restart: unless-stopped

  fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      BACKEND_URL: http://server:800
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - bugnet
    restart: unless-stopped

volumes:
  db_data:
